spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: dj125484
    url: jdbc:postgresql://localhost:5432/book_manage

server:
  port: 8088

mybatis:
  configuration:
    map-underscore-to-camel-case: true